name: Deploy NodeJS to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ajikan-game-node"
          heroku_email: "t.gribanow@gmail.com"
          buildpack: "heroku/nodejs"
          appdir: "node"
