name: Deploy NodeJS to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        working-directory: ./node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Build
        working-directory: ./node
        run: |
          npm ci
          npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ajikan-game-ci-test"
          heroku_email: "t.gribanow@gmail.com"
          appdir: "node"
          #buildpack: "heroku/nodejs"
